document.writeln("<!--copyright-->");
document.writeln("  <footer>");
document.writeln("    <div class=\'footer-outer\'>");
document.writeln("      <div class=\'footer-left\'>");
document.writeln("        <div class=\'ican-logo\'>");
document.writeln("          <img src=\'img/ican.png\' alt=\'艾肯娛樂\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'all-right\'>©<span>iCan</span>Entertainment Co.,Ltd. All Rights Reserved.</div>");
document.writeln("      </div>");
document.writeln("      <div class=\'logos\'>");
document.writeln("        <img src=\'img/c-logo.svg\' alt='' class=\'c-logo\'>");
document.writeln("      </div>");
document.writeln("      <div class=\'footer-right\'>");
document.writeln("        <div class=\'classLevel\'>");
document.writeln("          <img src=\'img/12+.png\' alt=\'12+\'>");
document.writeln("        </div>");
document.writeln("        <div class=\'classTxt\'>");
document.writeln("              ◆ 本遊戲涉及輕微性暗示、不當言語及暴力，角色穿著突顯胸、臀之服飾。");
document.writeln("          <br>◆ 注意使用時間，請避免沉迷遊戲。");
document.writeln("          <br>◆ 遊戲部分內容需另外支付費用。");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </footer>");